// build.zig — zig build port of the chimerautils meson build.
//
// Data-driven: the per-tool inventory lives in build-data/targets.json
// (extracted from the meson.build files). System dependency probes live in
// build-data/deps.json, generated by ./zig-configure.sh (a conservative
// default is committed so a bare `zig build` still works). Tools with code
// generation or other special needs are handled explicitly below.
// Meson remains the reference build.

const std = @import("std");
const builtin = @import("builtin");

const Target = struct {
    name: []const u8,
    dir: []const u8,
    type: []const u8,
    sources: []const []const u8 = &.{},
    c_args: []const []const u8 = &.{},
    link_with: []const []const u8 = &.{},
    sys_deps: []const []const u8 = &.{},
    enabled_by_default: bool = true,
};

const Deps = struct {
    ncurses: ?[]const u8 = null,
    tinfo: ?[]const u8 = null,
    acl: bool = false,
    xo: bool = false,
    crypto: bool = false,
    ssl: bool = false,
    edit: bool = false,
    z: bool = false,
    bz2: bool = false,
    lzma: bool = false,
    zstd: bool = false,
    selinux: bool = false,
    byacc: bool = false,
    flex: bool = false,
};

var deps: Deps = undefined;

fn loadDeps(b: *std.Build) void {
    deps = std.json.parseFromSliceLeaky(
        Deps,
        b.allocator,
        @embedFile("build-data/deps.json"),
        .{ .ignore_unknown_fields = true },
    ) catch @panic("cannot parse build-data/deps.json (run ./zig-configure.sh)");
}

const targets_json = @embedFile("build-data/targets.json");

const global_c_flags = [_][]const u8{
    "-std=gnu99",
    "-D_GNU_SOURCE",
    "-D_FILE_OFFSET_BITS=64",
    "-D_CHIMERAUTILS_BUILD",
    "-Dlint",
    "-Wno-unused-result",
    "-Wno-string-plus-int",
};

var skipped_buf: [256][]const u8 = undefined;
var skipped_len: usize = 0;

fn skip(b: *std.Build, name: []const u8, why: []const u8) void {
    if (skipped_len < skipped_buf.len) {
        skipped_buf[skipped_len] = b.fmt("{s} ({s})", .{ name, why });
        skipped_len += 1;
    }
}

/// Resolve a sys_deps vocabulary entry to a library name to link, or null
/// when the dependency is unavailable per build-data/deps.json.
fn resolveSysDep(dep: []const u8) ?[]const u8 {
    const eq = std.mem.eql;
    if (eq(u8, dep, "m") or eq(u8, dep, "pthread")) return dep;
    if (eq(u8, dep, "ncurses")) return deps.ncurses;
    if (eq(u8, dep, "tinfo")) return deps.tinfo;
    if (eq(u8, dep, "acl")) return if (deps.acl) "acl" else null;
    if (eq(u8, dep, "xo")) return if (deps.xo) "xo" else null;
    if (eq(u8, dep, "crypto")) return if (deps.crypto) "crypto" else null;
    if (eq(u8, dep, "ssl")) return if (deps.ssl) "ssl" else null;
    if (eq(u8, dep, "edit")) return if (deps.edit) "edit" else null;
    if (eq(u8, dep, "z")) return if (deps.z) "z" else null;
    if (eq(u8, dep, "bz2")) return if (deps.bz2) "bz2" else null;
    if (eq(u8, dep, "lzma")) return if (deps.lzma) "lzma" else null;
    if (eq(u8, dep, "zstd")) return if (deps.zstd) "zstd" else null;
    if (eq(u8, dep, "selinux")) return if (deps.selinux) "selinux" else null;
    return null; // pam, pam_misc, anything unknown
}

fn mkModule(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode, is_cpp: bool) *std.Build.Module {
    return b.createModule(.{
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .link_libcpp = is_cpp,
    });
}

fn hasCpp(sources: []const []const u8) bool {
    for (sources) |s| {
        if (std.mem.endsWith(u8, s, ".cc")) return true;
    }
    return false;
}

const YaccOut = struct { c: std.Build.LazyPath, h: std.Build.LazyPath };

fn runByacc(b: *std.Build, dir: []const u8, input: []const u8, outbase: []const u8, dash_d: bool) YaccOut {
    const run = b.addSystemCommand(if (dash_d)
        &.{ "byacc", "-d", "-H" }
    else
        &.{ "byacc", "-H" });
    const h = run.addOutputFileArg(b.fmt("{s}.h", .{outbase}));
    run.addArg("-o");
    const c = run.addOutputFileArg(b.fmt("{s}.c", .{outbase}));
    run.addFileArg(b.path(b.fmt("{s}/{s}", .{ dir, input })));
    return .{ .c = c, .h = h };
}

fn runFlex(b: *std.Build, dir: []const u8, input: []const u8, outbase: []const u8) std.Build.LazyPath {
    const run = b.addSystemCommand(&.{ "flex", "-o" });
    const c = run.addOutputFileArg(b.fmt("{s}.c", .{outbase}));
    run.addFileArg(b.path(b.fmt("{s}/{s}", .{ dir, input })));
    return c;
}

/// Run a shell command (relative paths, cwd is the build root), tracking
/// `inputs` as dependencies, capturing stdout into a named file.
fn capture(b: *std.Build, basename: []const u8, argv: []const []const u8, inputs: []const []const u8) std.Build.LazyPath {
    const run = b.addSystemCommand(argv);
    for (inputs) |i| run.addFileInput(b.path(i));
    return run.captureStdOut(.{ .basename = basename });
}

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    // ReleaseFast matches the meson (gcc -O2) reference behavior. Building
    // with -Doptimize=ReleaseSafe or Debug enables zig's UB checks, which
    // currently fire on latent upstream UB — see SECURITY-FINDINGS.md.
    const optimize = b.option(std.builtin.OptimizeMode, "optimize", "optimization mode") orelse .ReleaseFast;
    const arena = b.allocator;
    loadDeps(b);

    // deps.json was probed for the host; none of it applies when
    // cross-compiling.  Zero the system deps so tools needing external
    // libraries are skipped instead of failing to link against host
    // libraries.  byacc/flex run on the host at build time, keep those.
    if (target.result.cpu.arch != builtin.cpu.arch or
        target.result.os.tag != builtin.os.tag) {
        deps = .{ .byacc = deps.byacc, .flex = deps.flex };
    }

    const have_ssl = deps.ssl and deps.crypto;

    // ----- config-compat.h ---------------------------------------------
    const config_compat = b.addConfigHeader(.{ .include_path = "config-compat.h" }, .{
        .PROJECT_NAME = "chimerautils",
        .PROJECT_VERSION = "15.1.0",
        .LIBEXECDIR = "/usr/local/libexec",
        .HAVE_STRTOQ = true,
    });

    // src.custom tools include a plain "config.h" with name/version
    const custom_config = b.addConfigHeader(.{ .include_path = "config.h" }, .{
        .PROJECT_NAME = "chimerautils",
        .PROJECT_VERSION = "15.1.0",
    });

    // worst case: base + selinux + 2 Wno + 5 harden + 3 prod-sanitize
    var gflags_buf: [global_c_flags.len + 11][]const u8 = undefined;
    var gflags_len: usize = global_c_flags.len;
    @memcpy(gflags_buf[0..global_c_flags.len], &global_c_flags);
    if (deps.selinux) {
        gflags_buf[gflags_len] = "-DHAVE_SELINUX";
        gflags_len += 1;
    }
    gflags_buf[gflags_len] = "-Wno-error=implicit-function-declaration";
    gflags_len += 1;
    gflags_buf[gflags_len] = "-Wno-incompatible-pointer-types-discards-qualifiers";
    gflags_len += 1;

    // Hardening (default on; disable with -Dharden=false)
    const harden = b.option(bool, "harden", "enable hardening flags (stack protector, auto-var-init, fortify)") orelse true;
    if (harden) {
        for ([_][]const u8{
            "-fstack-protector-strong",
            "-fstack-clash-protection",
            "-ftrivial-auto-var-init=zero",
            // zig pre-defines _FORTIFY_SOURCE in safe build modes
            "-U_FORTIFY_SOURCE",
            "-D_FORTIFY_SOURCE=3",
        }) |f| {
            gflags_buf[gflags_len] = f;
            gflags_len += 1;
        }
    }
    // Production trap-mode UB checks (default off; enable with
    // -Dprod-sanitize=true): bounds + object-size sanitizers with the
    // minimal runtime, trapping (ud2) instead of reporting.
    const prod_sanitize = b.option(bool, "prod-sanitize", "enable trap-mode bounds/object-size sanitizers") orelse false;
    if (prod_sanitize) {
        for ([_][]const u8{
            "-fsanitize=bounds,object-size",
            "-fsanitize-minimal-runtime",
            "-fsanitize-trap=bounds,object-size",
        }) |f| {
            gflags_buf[gflags_len] = f;
            gflags_len += 1;
        }
    }
    const gflags = gflags_buf[0..gflags_len];

    // ----- safestr static library (Zig implementation, C ABI) ----------
    const safestr_mod = b.createModule(.{
        .target = target,
        .optimize = optimize,
        .root_source_file = b.path("src.safestr/safestr.zig"),
        .link_libc = true,
    });
    const libsafestr = b.addLibrary(.{ .name = "safestr", .linkage = .static, .root_module = safestr_mod });
    b.installArtifact(libsafestr);
    b.installFile("src.safestr/safestr.h", "include/safestr.h");

    // ----- test step: zig unit tests + C ABI consumer test --------------
    const test_step = b.step("test", "run safestr tests and smoke checks");
    const safestr_unit = b.addTest(.{ .root_module = safestr_mod });
    test_step.dependOn(&b.addRunArtifact(safestr_unit).step);

    const c_test_mod = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true });
    c_test_mod.addCSourceFile(.{ .file = b.path("src.safestr/test/c_safestr_test.c"), .flags = &.{} });
    c_test_mod.addIncludePath(b.path("src.safestr"));
    c_test_mod.linkLibrary(libsafestr);
    const c_test = b.addExecutable(.{ .name = "c_safestr_test", .root_module = c_test_mod });
    test_step.dependOn(&b.addRunArtifact(c_test).step);

    // ----- internal static libraries ------------------------------------
    // compat
    const compat_flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{"-DHAVE_NBTOOL_CONFIG_H"} });
    const compat_mod = mkModule(b, target, optimize, false);
    compat_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/compat"), .files = &compat_sources, .flags = compat_flags });
    compat_mod.addCSourceFiles(.{ .root = b.path("src.compat"), .files = &src_compat_sources, .flags = compat_flags });
    compat_mod.addIncludePath(b.path("include"));
    compat_mod.addIncludePath(b.path("src.freebsd/include"));
    compat_mod.addConfigHeader(config_compat);
    const libcompat = b.addLibrary(.{ .name = "compat", .linkage = .static, .root_module = compat_mod });

    // util_static (also compiled into the shared libchimerautils below)
    const util_mod = mkModule(b, target, optimize, false);
    util_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/util"), .files = &util_sources, .flags = gflags });
    util_mod.addIncludePath(b.path("include"));
    util_mod.addIncludePath(b.path("src.freebsd/include"));
    util_mod.addConfigHeader(config_compat);
    const libutil = b.addLibrary(.{ .name = "util_static", .linkage = .static, .root_module = util_mod });

    // shared libchimerautils
    const chimera_mod = mkModule(b, target, optimize, false);
    chimera_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/util"), .files = &util_sources, .flags = gflags });
    chimera_mod.addIncludePath(b.path("include"));
    chimera_mod.addIncludePath(b.path("src.freebsd/include"));
    chimera_mod.addConfigHeader(config_compat);
    const libchimera = b.addLibrary(.{ .name = "chimerautils", .linkage = .dynamic, .root_module = chimera_mod });
    b.installArtifact(libchimera);

    // dbcompat
    const db_flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{"-D__DBINTERFACE_PRIVATE"} });
    const db_mod = mkModule(b, target, optimize, false);
    db_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/dbcompat"), .files = &dbcompat_sources, .flags = db_flags });
    db_mod.addIncludePath(b.path("include"));
    db_mod.addIncludePath(b.path("src.freebsd/include"));
    db_mod.addIncludePath(b.path("src.freebsd/dbinclude"));
    db_mod.addConfigHeader(config_compat);
    const libdbcompat = b.addLibrary(.{ .name = "dbcompat", .linkage = .static, .root_module = db_mod });

    // libmp
    const mp_mod = mkModule(b, target, optimize, false);
    mp_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/libmp"), .files = &.{"mpasbn.c"}, .flags = gflags });
    mp_mod.addIncludePath(b.path("include"));
    mp_mod.addIncludePath(b.path("src.freebsd/include"));
    mp_mod.addIncludePath(b.path("src.freebsd/libmp"));
    mp_mod.addConfigHeader(config_compat);
    const libmp = b.addLibrary(.{ .name = "libmp", .linkage = .static, .root_module = mp_mod });

    // libstdbuf shared module
    const stdbuf_mod = mkModule(b, target, optimize, false);
    stdbuf_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/libstdbuf"), .files = &.{"stdbuf.c"}, .flags = gflags });
    stdbuf_mod.addIncludePath(b.path("include"));
    stdbuf_mod.addConfigHeader(config_compat);
    const libstdbuf = b.addLibrary(.{ .name = "stdbuf", .linkage = .dynamic, .root_module = stdbuf_mod });
    b.installArtifact(libstdbuf);

    // libfetch (needs OpenSSL + generated error headers)
    var libfetch_opt: ?*std.Build.Step.Compile = null;
    if (have_ssl) {
        const lf_flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{ "-DFTP_COMBINE_CWDS", "-DINET6", "-DWITH_SSL", "-Wno-deprecated-declarations" } });
        const ftperr = capture(b, "ftperr.h", &.{ "src.freebsd/libfetch/gen_errors.sh", "ftp", "src.freebsd/libfetch/ftp.errors" }, &.{"src.freebsd/libfetch/ftp.errors"});
        const httperr = capture(b, "httperr.h", &.{ "src.freebsd/libfetch/gen_errors.sh", "http", "src.freebsd/libfetch/http.errors" }, &.{"src.freebsd/libfetch/http.errors"});
        const lf_mod = mkModule(b, target, optimize, false);
        lf_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/libfetch"), .files = &libfetch_sources, .flags = lf_flags });
        lf_mod.addIncludePath(b.path("include"));
        lf_mod.addIncludePath(b.path("src.freebsd/include"));
        lf_mod.addIncludePath(b.path("src.freebsd/libfetch"));
        lf_mod.addIncludePath(ftperr.dirname());
        lf_mod.addIncludePath(httperr.dirname());
        lf_mod.addConfigHeader(config_compat);
        lf_mod.linkLibrary(libcompat);
        libfetch_opt = b.addLibrary(.{ .name = "libfetch", .linkage = .static, .root_module = lf_mod });
    } else {
        skip(b, "libfetch", "openssl not found");
        skip(b, "fetch", "openssl not found");
    }

    // ----- internal lib lookup ------------------------------------------
    const libFor = struct {
        fn get(
            name: []const u8,
            compat: *std.Build.Step.Compile,
            util: *std.Build.Step.Compile,
            db: *std.Build.Step.Compile,
            mp: *std.Build.Step.Compile,
            fetch: ?*std.Build.Step.Compile,
        ) ?*std.Build.Step.Compile {
            const eq = std.mem.eql;
            if (eq(u8, name, "compat")) return compat;
            if (eq(u8, name, "util_static")) return util;
            if (eq(u8, name, "dbcompat")) return db;
            if (eq(u8, name, "libmp")) return mp;
            if (eq(u8, name, "libfetch")) return fetch;
            return null;
        }
    }.get;

    // ----- special tools -------------------------------------------------

    // expr (yacc-only source)
    if (deps.byacc) {
        const y = runByacc(b, "src.freebsd/coreutils/expr", "expr.y", "expr", false);
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFile(.{ .file = y.c, .flags = gflags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(y.h.dirname());
        m.addConfigHeader(config_compat);
        const exe = b.addExecutable(.{ .name = "expr", .root_module = m });
        b.installArtifact(exe);
    } else skip(b, "expr", "byacc not found");

    // m4 (yacc + lex)
    if (deps.byacc and deps.flex) {
        const y = runByacc(b, "src.freebsd/m4", "parser.y", "parser", false);
        const tok = runFlex(b, "src.freebsd/m4", "tokenizer.l", "tokenizer");
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path("src.freebsd/m4"), .files = &m4_sources, .flags = gflags });
        m.addCSourceFile(.{ .file = y.c, .flags = gflags });
        m.addCSourceFile(.{ .file = tok, .flags = gflags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path("src.freebsd/include"));
        m.addIncludePath(y.h.dirname());
        m.addConfigHeader(config_compat);
        m.linkLibrary(libcompat);
        m.linkSystemLibrary("m", .{});
        const exe = b.addExecutable(.{ .name = "m4", .root_module = m });
        b.installArtifact(exe);
    } else skip(b, "m4", "byacc/flex not found");

    // find (yacc getdate, needs libacl)
    if (deps.byacc) blk: {
        const acl_lib = resolveSysDep("acl") orelse {
            skip(b, "find", "libacl not found");
            break :blk;
        };
        const y = runByacc(b, "src.freebsd/findutils/find", "getdate.y", "getdate", false);
        const flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{ "-DQUAD_MAX=LONG_MAX", "-DMAXLOGNAME=_POSIX_LOGIN_NAME_MAX", "-DACL_TYPE_NFS4", "-fwrapv" } });
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path("src.freebsd/findutils/find"), .files = &find_sources, .flags = flags });
        m.addCSourceFile(.{ .file = y.c, .flags = flags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path("src.freebsd/include"));
        m.addIncludePath(y.h.dirname());
        m.addConfigHeader(config_compat);
        m.linkLibrary(libcompat);
        m.linkLibrary(libutil);
        m.linkSystemLibrary(acl_lib, .{});
        const exe = b.addExecutable(.{ .name = "find", .root_module = m });
        b.installArtifact(exe);
    } else skip(b, "find", "byacc not found");

    // awk (byacc -d + native maketab)
    if (deps.byacc) {
        const y = runByacc(b, "src.freebsd/awk", "awkgram.y", "awkgram.tab", true);
        const mt_mod = mkModule(b, target, optimize, false);
        mt_mod.addCSourceFiles(.{ .root = b.path("src.freebsd/awk"), .files = &.{"maketab.c"}, .flags = gflags });
        mt_mod.addIncludePath(b.path("include"));
        mt_mod.addIncludePath(b.path("src.freebsd/awk"));
        mt_mod.addIncludePath(y.h.dirname());
        mt_mod.addConfigHeader(config_compat);
        const maketab = b.addExecutable(.{ .name = "maketab", .root_module = mt_mod });
        const mt_run = b.addRunArtifact(maketab);
        mt_run.addFileArg(y.h);
        const proctab = mt_run.captureStdOut(.{ .basename = "proctab.c" });
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path("src.freebsd/awk"), .files = &awk_sources, .flags = gflags });
        m.addCSourceFile(.{ .file = y.c, .flags = gflags });
        m.addCSourceFile(.{ .file = proctab, .flags = gflags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path("src.freebsd/awk"));
        m.addIncludePath(y.h.dirname());
        m.addConfigHeader(config_compat);
        m.linkSystemLibrary("m", .{});
        const exe = b.addExecutable(.{ .name = "awk", .root_module = m });
        b.installArtifact(exe);
    } else skip(b, "awk", "byacc not found");

    // sh (four generators + bltins_lib)
    {
        const shdir = "src.freebsd/sh";
        const mknodes_mod = mkModule(b, target, optimize, false);
        mknodes_mod.addCSourceFiles(.{ .root = b.path(shdir), .files = &.{"mknodes.c"}, .flags = gflags });
        mknodes_mod.addIncludePath(b.path("include"));
        mknodes_mod.addConfigHeader(config_compat);
        const mknodes = b.addExecutable(.{ .name = "mknodes", .root_module = mknodes_mod });

        const mksyntax_mod = mkModule(b, target, optimize, false);
        mksyntax_mod.addCSourceFiles(.{ .root = b.path(shdir), .files = &.{"mksyntax.c"}, .flags = gflags });
        mksyntax_mod.addIncludePath(b.path("include"));
        mksyntax_mod.addConfigHeader(config_compat);
        const mksyntax = b.addExecutable(.{ .name = "mksyntax", .root_module = mksyntax_mod });

        const mkbuiltins = b.addSystemCommand(&.{ "src.freebsd/sh/mkbuiltins", "src.freebsd/sh" });
        const bl_dir = mkbuiltins.addOutputDirectoryArg("shbuiltins");
        for (sh_inputs) |f| mkbuiltins.addFileInput(b.path(f));
        const builtins_c = try bl_dir.join(arena, "builtins.c");

        const mktokens = b.addSystemCommand(&.{"src.freebsd/sh/mktokens"});
        const tok_dir = mktokens.addOutputDirectoryArg("shtokens");

        const nodes_run = b.addRunArtifact(mknodes);
        nodes_run.addFileArg(b.path("src.freebsd/sh/nodetypes"));
        nodes_run.addFileArg(b.path("src.freebsd/sh/nodes.c.pat"));
        const nodes_h = nodes_run.addOutputFileArg("nodes.h");
        const nodes_c = nodes_run.addOutputFileArg("nodes.c");

        const syntax_run = b.addRunArtifact(mksyntax);
        const syntax_h = syntax_run.addOutputFileArg("syntax.h");
        const syntax_c = syntax_run.addOutputFileArg("syntax.c");

        // bltins_lib
        const bl_flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{"-DSHELL"} });
        const bl_mod = mkModule(b, target, optimize, false);
        bl_mod.addCSourceFiles(.{ .root = b.path(shdir), .files = &.{"bltin/echo.c"}, .flags = bl_flags });
        bl_mod.addCSourceFile(.{ .file = b.path("src.freebsd/miscutils/kill/kill.c"), .flags = bl_flags });
        bl_mod.addCSourceFile(.{ .file = b.path("src.freebsd/coreutils/printf/printf.c"), .flags = bl_flags });
        bl_mod.addCSourceFile(.{ .file = b.path("src.freebsd/coreutils/test/test.c"), .flags = bl_flags });
        bl_mod.addCSourceFile(.{ .file = builtins_c, .flags = bl_flags });
        bl_mod.addIncludePath(b.path("include"));
        bl_mod.addIncludePath(b.path(shdir));
        bl_mod.addIncludePath(bl_dir);
        bl_mod.addConfigHeader(config_compat);
        const bl = b.addLibrary(.{ .name = "bltins_lib", .linkage = .static, .root_module = bl_mod });

        // sh itself
        var sh_flags = try std.mem.concat(arena, []const u8, &.{gflags});
        if (!deps.edit) sh_flags = try std.mem.concat(arena, []const u8, &.{ sh_flags, &.{"-DNO_HISTORY"} });
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path(shdir), .files = &sh_sources, .flags = sh_flags });
        m.addCSourceFile(.{ .file = nodes_c, .flags = sh_flags });
        m.addCSourceFile(.{ .file = syntax_c, .flags = sh_flags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path(shdir));
        m.addIncludePath(bl_dir);
        m.addIncludePath(tok_dir);
        m.addIncludePath(nodes_h.dirname());
        m.addIncludePath(syntax_h.dirname());
        m.addConfigHeader(config_compat);
        m.linkLibrary(bl);
        m.linkLibrary(libcompat);
        if (deps.edit) m.linkSystemLibrary("edit", .{});
        const exe = b.addExecutable(.{ .name = "sh", .root_module = m });
        b.installArtifact(exe);
    }

    // nvi (config headers + generated headers)
    if (deps.ncurses != null) {
        const nvi_config = b.addConfigHeader(.{ .include_path = "config.h" }, .{
            .USE_WIDECHAR = true,
            .USE_ICONV = true,
            .ICONV_TRADITIONAL = true,
            .HAVE_PTY_H = true,
            .HAVE_TERM_H = true,
            .HAVE_NCURSESW_NCURSES_H = true,
        });
        const pathnames = b.addConfigHeader(.{
            .style = .{ .autoconf_at = b.path("src.freebsd/nvi/files/pathnames.h.in") },
            .include_path = "pathnames.h",
        }, .{
            .vi_cv_path_msgcat = "/usr/local/share/vi/catalog/",
            .vi_cv_path_preserve = "/var/tmp/vi.recover/",
        });
        const options_def_h = capture(b, "options_def.h", &.{ "awk", "-f", "src.freebsd/nvi/common/options.awk", "src.freebsd/nvi/common/options.c" }, &.{ "src.freebsd/nvi/common/options.awk", "src.freebsd/nvi/common/options.c" });
        const ex_def_h = capture(b, "ex_def.h", &.{ "awk", "-f", "src.freebsd/nvi/ex/ex.awk", "src.freebsd/nvi/ex/ex_cmd.c" }, &.{ "src.freebsd/nvi/ex/ex.awk", "src.freebsd/nvi/ex/ex_cmd.c" });
        const version_h = capture(b, "version.h", &.{ "src.freebsd/nvi/gen_ex_version_h.sh", "src.freebsd/nvi/README" }, &.{"src.freebsd/nvi/README"});
        const cl_ext = capture(b, "cl_extern.h", try std.mem.concat(arena, []const u8, &.{ &.{ "src.freebsd/nvi/gen_extern_h.sh", "cl" }, &nvi_inputs }), &nvi_inputs);
        const common_ext = capture(b, "common_extern.h", try std.mem.concat(arena, []const u8, &.{ &.{ "src.freebsd/nvi/gen_extern_h.sh", "common" }, &nvi_inputs }), &nvi_inputs);
        const ex_ext = capture(b, "ex_extern.h", try std.mem.concat(arena, []const u8, &.{ &.{ "src.freebsd/nvi/gen_extern_h.sh", "ex" }, &nvi_inputs }), &nvi_inputs);
        const vi_ext = capture(b, "vi_extern.h", try std.mem.concat(arena, []const u8, &.{ &.{ "src.freebsd/nvi/gen_extern_h.sh", "vi" }, &nvi_inputs }), &nvi_inputs);

        const nvi_flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{ "-D__REGEX_PRIVATE", "-D_XOPEN_SOURCE=600", "-DHAVE_NCURSESW_NCURSES_H", "-Wno-unused-but-set-variable", "-Wno-unused-parameter", "-Wno-sign-compare", "-Wno-missing-field-initializers" } });
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path("src.freebsd/nvi"), .files = &nvi_sources, .flags = nvi_flags });
        m.addIncludePath(b.path("src.freebsd/nvi"));
        m.addIncludePath(b.path("src.freebsd/nvi/regex"));
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path("src.freebsd/include"));
        m.addIncludePath(b.path("src.freebsd/dbinclude"));
        m.addIncludePath(options_def_h.dirname());
        m.addIncludePath(ex_def_h.dirname());
        m.addIncludePath(version_h.dirname());
        m.addIncludePath(cl_ext.dirname());
        m.addIncludePath(common_ext.dirname());
        m.addIncludePath(ex_ext.dirname());
        m.addIncludePath(vi_ext.dirname());
        m.addConfigHeader(config_compat);
        m.addConfigHeader(nvi_config);
        m.addConfigHeader(pathnames);
        m.linkLibrary(libcompat);
        m.linkLibrary(libdbcompat);
        m.linkSystemLibrary(deps.ncurses.?, .{});
        const exe = b.addExecutable(.{ .name = "vi", .root_module = m });
        b.installArtifact(exe);
    } else skip(b, "vi", "ncurses not found");

    // stdbuf executable (needs LIBSTDBUF path define)
    {
        const prefix = b.option([]const u8, "prefix", "installation prefix used for LIBSTDBUF") orelse "/usr/local";
        const libpath = b.fmt("-DLIBSTDBUF=\"{s}/lib/libstdbuf.so\"", .{prefix});
        const flags = try std.mem.concat(arena, []const u8, &.{ gflags, &.{libpath} });
        const m = mkModule(b, target, optimize, false);
        m.addCSourceFiles(.{ .root = b.path("src.freebsd/coreutils/stdbuf"), .files = &.{"stdbuf.c"}, .flags = flags });
        m.addIncludePath(b.path("include"));
        m.addConfigHeader(config_compat);
        const exe = b.addExecutable(.{ .name = "stdbuf", .root_module = m });
        b.installArtifact(exe);
    }

    // ----- generic targets from build-data/targets.json ------------------
    const parsed = try std.json.parseFromSlice(
        struct { targets: []Target },
        arena,
        targets_json,
        .{ .ignore_unknown_fields = true },
    );
    defer parsed.deinit();

    // dirs handled by explicit code above
    const special_dirs = [_][]const u8{
        "src.freebsd/coreutils/expr",
        "src.freebsd/m4",
        "src.freebsd/findutils/find",
        "src.freebsd/awk",
        "src.freebsd/sh",
        "src.freebsd/nvi",
        "src.freebsd/coreutils/stdbuf",
    };
    // non-executable targets and build-time-only tools, built above or skipped
    const skip_names = [_][]const u8{
        "compat",       "util_static", "dbcompat", "libmp",   "libfetch",
        "chimerautils", "bltins_lib",  "maketab",  "mknodes", "mksyntax",
    };

    outer: for (parsed.value.targets) |t| {
        if (!t.enabled_by_default) continue;
        if (!std.mem.eql(u8, t.type, "executable")) continue;
        for (skip_names) |n| {
            if (std.mem.eql(u8, t.name, n)) continue :outer;
        }
        for (special_dirs) |d| {
            if (std.mem.eql(u8, t.dir, d)) continue :outer;
        }

        const is_cpp = hasCpp(t.sources);
        const m = mkModule(b, target, optimize, is_cpp);
        // -std=gnu99 is only valid for C
        const base_flags = if (is_cpp) gflags[1..] else gflags;
        var flags = try std.mem.concat(arena, []const u8, &.{ base_flags, t.c_args });
        // the diff parser's line-number arithmetic is allowed to wrap
        if (std.mem.eql(u8, t.dir, "src.freebsd/patch"))
            flags = try std.mem.concat(arena, []const u8, &.{ flags, &.{"-fwrapv"} });
        m.addCSourceFiles(.{ .root = b.path(t.dir), .files = t.sources, .flags = flags });
        m.addIncludePath(b.path("include"));
        m.addIncludePath(b.path("src.freebsd/include"));
        m.addConfigHeader(config_compat);

        // extra include dirs implied by linked libs / known layouts
        var need_dbinc = false;
        var need_mpinc = false;
        for (t.link_with) |lw| {
            if (std.mem.eql(u8, lw, "dbcompat")) need_dbinc = true;
            if (std.mem.eql(u8, lw, "libmp")) need_mpinc = true;
            if (std.mem.eql(u8, lw, "libfetch")) m.addIncludePath(b.path("src.freebsd/libfetch"));
        }
        if (need_dbinc) m.addIncludePath(b.path("src.freebsd/dbinclude"));
        if (need_mpinc) m.addIncludePath(b.path("src.freebsd/libmp"));
        if (std.mem.startsWith(u8, t.dir, "src.custom")) {
            m.addIncludePath(b.path("src.custom"));
            m.addConfigHeader(custom_config);
        }
        if (std.mem.eql(u8, t.dir, "src.freebsd/tip")) {
            m.addIncludePath(b.path("src.freebsd/tip"));
            m.addIncludePath(b.path("src.freebsd/tip/tip"));
        }
        if (std.mem.eql(u8, t.dir, "src.freebsd/miscutils/ncal")) m.addIncludePath(b.path("src.freebsd/miscutils/ncal"));
        if (std.mem.eql(u8, t.dir, "src.freebsd/telnet")) {
            m.addIncludePath(b.path("src.freebsd/telnet"));
            m.addIncludePath(b.path("src.freebsd/telnet/libtelnet"));
        }
        if (std.mem.eql(u8, t.dir, "src.freebsd/findutils/locate/code") or
            std.mem.eql(u8, t.dir, "src.freebsd/findutils/locate/bigram"))
        {
            m.addIncludePath(b.path("src.freebsd/findutils/locate/locate"));
        }

        for (t.link_with) |lw| {
            const lib = libFor(lw, libcompat, libutil, libdbcompat, libmp, libfetch_opt) orelse {
                skip(b, t.name, b.fmt("internal lib {s} unavailable", .{lw}));
                continue :outer;
            };
            m.linkLibrary(lib);
            // libfetch carries no ssl/crypto linkage of its own (static
            // archive); consumers must link OpenSSL themselves.
            if (std.mem.eql(u8, lw, "libfetch")) {
                m.linkSystemLibrary("ssl", .{});
                m.linkSystemLibrary("crypto", .{});
            }
        }
        for (t.sys_deps) |dep| {
            const lib = resolveSysDep(dep) orelse {
                skip(b, t.name, b.fmt("dependency {s} not found", .{dep}));
                continue :outer;
            };
            m.linkSystemLibrary(lib, .{});
        }

        const exe = b.addExecutable(.{ .name = t.name, .root_module = m });
        b.installArtifact(exe);
    }

    if (skipped_len > 0) {
        std.debug.print("\nskipped {d} target(s):\n", .{skipped_len});
        for (skipped_buf[0..skipped_len]) |s| std.debug.print("  - {s}\n", .{s});
    }
}

const compat_sources = [_][]const u8{
    "getbsize.c",   "heapsort.c", "humanize_number.c", "merge.c",
    "mktemp.c",     "ohash.c",    "setmode.c",         "strmode.c",
    "strftime.c",   "strptime.c", "stringlist.c",      "expand_number.c",
    "unvis.c",      "vis.c",
};

const src_compat_sources = [_][]const u8{
    "b64.c", "err.c", "strlfuncs.c", "signames.c", "strtonum.c", "reallocf.c",
};

const util_sources = [_][]const u8{
    "fts.c", "rpmatch.c",
};

const dbcompat_sources = [_][]const u8{
    "btree/bt_close.c",   "btree/bt_conv.c",    "btree/bt_debug.c",
    "btree/bt_delete.c",  "btree/bt_get.c",     "btree/bt_open.c",
    "btree/bt_overflow.c", "btree/bt_page.c",   "btree/bt_put.c",
    "btree/bt_search.c",  "btree/bt_seq.c",     "btree/bt_split.c",
    "btree/bt_utils.c",   "recno/rec_close.c",  "recno/rec_delete.c",
    "recno/rec_get.c",    "recno/rec_open.c",   "recno/rec_put.c",
    "recno/rec_search.c", "recno/rec_seq.c",    "recno/rec_utils.c",
    "db.c",               "mpool.c",
};

const libfetch_sources = [_][]const u8{
    "fetch.c", "common.c", "ftp.c", "http.c", "file.c",
};

const m4_sources = [_][]const u8{
    "eval.c", "expr.c", "look.c", "main.c", "misc.c", "gnum4.c", "trace.c",
};

const find_sources = [_][]const u8{
    "find.c", "function.c", "ls.c", "main.c", "misc.c", "operator.c", "option.c", "printf.c",
};

const awk_sources = [_][]const u8{
    "b.c", "lex.c", "lib.c", "main.c", "parse.c", "run.c", "tran.c",
};

const sh_sources = [_][]const u8{
    "alias.c",    "arith_yacc.c", "arith_yylex.c", "cd.c",      "error.c",
    "eval.c",     "exec.c",       "expand.c",      "histedit.c", "input.c",
    "jobs.c",     "mail.c",       "main.c",        "memalloc.c", "miscbltin.c",
    "mystring.c", "options.c",    "output.c",      "parser.c",   "redir.c",
    "show.c",     "trap.c",       "var.c",
};

// files mkbuiltins reads (dependency tracking)
const sh_inputs = [_][]const u8{
    "src.freebsd/sh/shell.h",
    "src.freebsd/sh/mkbuiltins",
    "src.freebsd/sh/bltin/echo.c",
    "src.freebsd/miscutils/kill/kill.c",
    "src.freebsd/coreutils/printf/printf.c",
    "src.freebsd/coreutils/test/test.c",
};

const nvi_sources = [_][]const u8{
    "cl/cl_funcs.c",      "cl/cl_main.c",        "cl/cl_read.c",
    "cl/cl_screen.c",     "cl/cl_term.c",        "ex/ex.c",
    "ex/ex_abbrev.c",     "ex/ex_append.c",      "ex/ex_args.c",
    "ex/ex_argv.c",       "ex/ex_at.c",          "ex/ex_bang.c",
    "ex/ex_cd.c",         "ex/ex_cmd.c",         "ex/ex_cscope.c",
    "ex/ex_delete.c",     "ex/ex_display.c",     "ex/ex_edit.c",
    "ex/ex_equal.c",      "ex/ex_file.c",        "ex/ex_filter.c",
    "ex/ex_global.c",     "ex/ex_init.c",        "ex/ex_join.c",
    "ex/ex_map.c",        "ex/ex_mark.c",        "ex/ex_mkexrc.c",
    "ex/ex_move.c",       "ex/ex_open.c",        "ex/ex_preserve.c",
    "ex/ex_print.c",      "ex/ex_put.c",         "ex/ex_quit.c",
    "ex/ex_read.c",       "ex/ex_screen.c",      "ex/ex_script.c",
    "ex/ex_set.c",        "ex/ex_shell.c",       "ex/ex_shift.c",
    "ex/ex_source.c",     "ex/ex_stop.c",        "ex/ex_subst.c",
    "ex/ex_tag.c",        "ex/ex_txt.c",         "ex/ex_undo.c",
    "ex/ex_usage.c",      "ex/ex_util.c",        "ex/ex_version.c",
    "ex/ex_visual.c",     "ex/ex_write.c",       "ex/ex_yank.c",
    "ex/ex_z.c",          "vi/vi.c",             "vi/getc.c",
    "vi/v_at.c",          "vi/v_ch.c",           "vi/v_cmd.c",
    "vi/v_delete.c",      "vi/v_ex.c",           "vi/v_increment.c",
    "vi/v_init.c",        "vi/v_itxt.c",         "vi/v_left.c",
    "vi/v_mark.c",        "vi/v_match.c",        "vi/v_paragraph.c",
    "vi/v_put.c",         "vi/v_redraw.c",       "vi/v_replace.c",
    "vi/v_right.c",       "vi/v_screen.c",       "vi/v_scroll.c",
    "vi/v_search.c",      "vi/v_section.c",      "vi/v_sentence.c",
    "vi/v_status.c",      "vi/v_txt.c",          "vi/v_ulcase.c",
    "vi/v_undo.c",        "vi/v_util.c",         "vi/v_word.c",
    "vi/v_xchar.c",       "vi/v_yank.c",         "vi/v_z.c",
    "vi/v_zexit.c",       "vi/vs_line.c",        "vi/vs_msg.c",
    "vi/vs_refresh.c",    "vi/vs_relative.c",    "vi/vs_smap.c",
    "vi/vs_split.c",      "common/conv.c",       "common/cut.c",
    "common/delete.c",    "common/encoding.c",   "common/exf.c",
    "common/key.c",       "common/line.c",       "common/log.c",
    "common/main.c",      "common/mark.c",       "common/msg.c",
    "common/options.c",   "common/options_f.c",  "common/put.c",
    "common/recover.c",   "common/screen.c",     "common/search.c",
    "common/seq.c",       "common/util.c",       "regex/regcomp.c",
    "regex/regerror.c",   "regex/regexec.c",     "regex/regfree.c",
};

// same list, prefixed, for gen_extern_h.sh dependency tracking
const nvi_inputs = blk: {
    var out: [nvi_sources.len][]const u8 = undefined;
    for (nvi_sources, 0..) |s, i| out[i] = "src.freebsd/nvi/" ++ s;
    break :blk out;
};
