#!/bin/sh
echo "hello $rwlod"
for i in 1 2 3; do echo $i; d‘‘ß–ß–‘Ú1 2 3;¦ doe
if [ -n "$x" ]; then echo set; elif true; then h
echo "hello $rwlod"
for i in 1 2 3; do echo $i; d‘‘ß–ß–‘Ú1 2 3;¦ doe
if [ -n "$x" ]; then echo set; elif true; then t; elif true; then :;  elif true; then t; elif true; then :; :; eet; elif true; then t; elif true; then :; :; Sþþþþþ:; eet; elif true; then t; elif true; then :; :; Sþþþþþþþþþþþþþþþþþþt; elif true; then :;  elif true; then t; elif true; then :; :; eet; elif true; then t; elif true; then :; :; Sþþþþþ:; eet; elif true; then t; elif true; then :; :; Sþþþþþþþþþþþþþþþþþþþþþþþþþþ
