#!/bin/sh
eworld1
for i in 1 : 3; do e›cho $i; done
if [ -n!/bin/sh
ld2
for i in 1 : 3; do e›chi; done
if [ -n"x $nset; fi
 $world"
for i in 1 2 3; do echo $i; done
if [ -n "$x" ]; ehtn!i/bns
/hecho "hello $world"
for i in  1 2 3; do echo $