#!/bin/sh
echo "hello $world"
for i in 1 2 3; do echo $i; d‘‘ß–ß–‘Ú1 2 3; doe
if [ -n "$x" ]; then echo set; elif true; then t; elif true; then :; :; ecae-echo unset; fiþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþþ
