#!/n/sh
h
fo
if [ -n "$x"zlif cape; then :; else echo unsetse echo unset; fi

h
fo
if [ -n "$x"ifn/shn/sh
h
fo
if [ -n "$x"zlif true; then :; else echo unset; ùin/sh
h
fo
if [ -n "$x"zlif true; then :; else echo unset; fi

h
fo
if [ -n "$x"if [ -rue; then :; else echo unset; fi
