#!/bin/sh
echo "hello $world"
for i in 1 2 3; do echo $i; d‘‘ß–ß–‘Ú1 2 3;¦ doeÑß–ß–‘Ú1 2 3;¦ doe
if [ -n "$x" ]; then echo set; elif t!/bin/sh
echo "hello $world"

if [ -n "$x" ]; then echo set; elif t!/bin/sh
echo "hello $world"
for i in 1 2 3; do echo $i;‘ß––‘ ßd‘Ú1 2 3;¦ =doe
if [ -n "$x" ]; then echo set; e2 þþþþþþþþþþþ
